### ISSUE TITLE
Feature request: configurable time offset (only show connections in more than X seconds/minutes...)

### ISSUE THREAD

**Issue by TheMagnificent7** [neuhausf/swiss-public-transport-mod#1]
I like the integration and it works well for the most part. Getting some 429's at the moment from the API - not sure if that's just me or they're having issues.

One little feature request if possible: configurable time offset (via config file parameter or - ideally - in the frontend).

Reasoning: most people don't live right next (or in :)) to the bus stop; instead, it takes them a few minutes to get there. For someone living e.g. 5 minutes' walk from the bus stop, it makes no sense to show connections in 3 minutes from now. Additionally, if the bus stop is really busy (as most stops attached to main train stations are), these unusable connections clutter the interface.

I assume this can be done via a configurable offset parameter (e.g. a number of seconds) in the configuration file or - ideally - via a selectable button in the frontend (e.g. "show connections in 5 - 10 - 15 minutes", with one of the 5/10/15 being selectable). I would have done at least the config file part gladly myself, if only I knew any Python.

**Comment by Rudd-O** [comment]
I think you want this *in the card*, not here.  Rationale explained here: https://github.com/neuhausf/lovelace-swiss-stationboard/issues/3

**Comment by neuhausf** [comment]
Probably we should extend the sensor: the card should display a constant number of next connections. So the sensor has to fetch more connections and check, if its within walking range. If not, you must fetch another connection until the desired number of connections is reached. You can‘t do this all in the card, unless you fetch way more than necessary.

**Comment by Rudd-O** [comment]
I would argue otherwise, if I may.  If I want to get data from a sensor for two cards with different departure times, I would have to add the sensor integration twice, thus doubling the data fetch.  If we do it in the card (hide that which I can't walk fast enough to), then I only need to add the integration once, which keeps the data fetch constant.  Either way perhaps the default "fetch 15 minutes' worth of connections" is too small — the sensor should fetch an hour, and the card should cap the maximum number of connections shown (either by number or by time).

**Comment by TheMagnificent7** [comment]
Agree with the last point by @Rudd-O - for my "home stop" I currently have to list 30 connections to get the next 2-3 listings of the one meaningful bus for me. 
They run every 6 minutes, the stop is ~5 minutes away, so I usually get in the list:
- one leaving in 2 minutes (too soon)
- one leaving in 8 minutes (about right, but a bit too close)
- one leaving in 14 minutes (if I am lucky - which is a sure catch) - more often than not though, this is thrown off the list by the other 25+ connections from the same stop that I am not interested in (see my other FR - filter connections in/out).

One could argue that I could just do the math in my head even if I don't see the third connection above (if the second is at 13:23, then the third would be at 13:29, even if it's not explicitly displayed), but isn't being lazy the main driver of automating things? :)

Having the offset selectable in the frontend would also enable another use case - it's one thing if I am getting dressed to go (e.g. need a connection in 'now+15'), it's a different thing if I am just about to walk out the door ('now+10').

**Comment by Rudd-O** [comment]
> but isn't being lazy the main driver of automating things? :)

*amen brother*

I want to see my foyer panel show me exactly when the next catchable train or bus is available.  Having extra stuff is just going to give me anxiety (as it does today).

> Having the offset selectable in the frontend would also enable another use case - it's one thing if I am getting dressed to go (e.g. need a connection in 'now+15'), it's a different thing if I am just about to walk out the door ('now+10').

Did not think of this but yea, the panel in my master bathroom should show me this.

**Comment by Rudd-O** [comment]
Another thing of note is that prospective delays should perhaps be factored in, since a train that is "supposed to come" at 5 minutes should nominally not be shown, but if there's a 6 minute delay (unlikely, yes, but it happens sometimes), that's definitely a train I can catch at least from home.

**Comment by neuhausf** [comment]
> I would argue otherwise, if I may. If I want to get data from a sensor for two cards with different departure times, I would have to add the sensor integration twice, thus doubling the data fetch.

I don't agree: There are very few usecases to use the same sensor for two different stationboards. Most of the times you would add another sensor, thus doubling the data fetching anyway. If you would want to support different departure times for the _same_ location, you would need to fetch _a lot_ of connections - adding the sensor twice would make more sense.

>  Either way perhaps the default "fetch 15 minutes' worth of connections" is too small — the sensor should fetch an hour, and the card should cap the maximum number of connections shown (either by number or by time).

Here is the main problem (which leads to my suggestion to transfer the logic into the sensor): The transport.opendata.ch API doesn't support an "end" time (see [here](https://transport.opendata.ch/docs.html#stationboard)) - only a number of next connections is supported.
Example:
offset (=walking time): 10min
now: 20:00
-> fetch next 5 connections, result:
20:04 Bern
20:06 Biel
20:08 Zürich
20:10 Bus to XY
20:15 Bern
-> the first 4 connections would be filtered out. If you do the filtering in the [card](https://github.com/neuhausf/swiss-public-transport-mod/issues/1#:~:text=neuhausf/lovelace%2Dswiss%2Dstationboard%233), you would get only one line.

In the sensor however, you can do another fetch, if you see that you need more connections as most of the journeys have been filtered. You can even add the offset to query the stationboard-method and let the API do the job: now+offset (parameter datetime).

**Comment by neuhausf** [comment]
> Another thing of note is that prospective delays should perhaps be factored in, since a train that is "supposed to come" at 5 minutes should nominally not be shown, but if there's a 6 minute delay (unlikely, yes, but it happens sometimes), that's definitely a train I can catch at least from home.

The card already respects this. However, there is a problem: Every 90 seconds, the sensor provides new data. The current implementation fetches connections from now and the future, and overrides the delayed connections which are in the past.

The stationboard API provides a "departure time from" (parameter name is "datetime") parameter - I have to check, if past dates are allowed. And even then: What do you use for the negative offset? The last provided delay minus walking_time_offset?

**Comment by Rudd-O** [comment]
> The transport.opendata.ch API doesn't support an "end" time (see [here](https://transport.opendata.ch/docs.html#stationboard)) - only a number of next connections is supported.

Ask for a hundred next connections.  Limit what you display in the board card.  Who cares?  :-)  Doesn't cost extra.  Asking for the 10 connections cost the exact same as asking for the next 100 connections, because whatever you're asking for is in RAM at the server already.  You are not being charged by connection.

> I don't agree: There are very few usecases to use the same sensor for two different stationboards.

Users seem to disagree with your disagreement.

This is okay.  I can fork the stationboard card to support this use case.  It should be little to no effort to add a "suppress any connections in the next X minutes", and a bit more effort to do the same but exclude those who are delayed.

> Most of the times you would add another sensor, thus doubling the data fetching anyway.

Yes, this is true in *some* cases, but as you have read from other users, not *most*.

**Comment by neuhausf** [comment]
> This is okay. I can fork the stationboard card to support this use case. It should be little to no effort to add a "suppress any connections in the next X minutes", and a bit more effort to do the same but exclude those who are delayed.

Don‘t get me wrong: I would love to have these two features as well. But I don‘t think, that the frontend code is the right place for this. The backend sensor acts like a proxy. Note that the underlying python abstraction of the opendata API has to be extended as well, to allow fetching stationboard connections from the past.

I‘m happy to accept pull requests as well or to merge your fork. Happy coding and a nice weekend!

**Comment by Rudd-O** [comment]
> Note that the underlying python abstraction of the opendata API has to be extended as well, to allow fetching stationboard connections from the past.

Huh?  Why would that be necessary?  We're talking about suppressing display of events *in the near future*, why would the code need to fetch *events in the past*?

I think we're not talking about the same thing at all, and that may be what the problem is.

I also don't see the sensor as a "proxy".  The sensor is a scoped data view into SBB's opinion of the public transit right now and in the near future.  The display view should be able to enact user policy as to what to show *with respect to* the data currently present in the sensor.  Sensor fetches data, UI decides how to display it.

In this sense this is no different from the calendar view in HA — you can have a calendar sensor that has all known calendar events, and then your view can filter which events it will show and how far in the future.

**Comment by neuhausf** [comment]
Offset 10min
Delay 20min

you got the idea?

**Comment by Rudd-O** [comment]
If there's a delay of 20 minutes in a particular train I am perfectly fine with not seeing it onscreen and not getting it retrieved.  The current data set is perfect for my requirements and needs no change — I just need to change the javascript to hide anything whose actual predicted arrival time (w/ delays and all) happens before <offset>.
